# Server Configuration
server.port=8082

# Database (H2)
spring.datasource.url=jdbc:h2:mem:scolarite-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Keycloak configuration (pour la validation des tokens)
keycloak.auth-server-url=http://localhost:8081
keycloak.realm=scolarite

# Admin credentials pour Keycloak (uniquement pour le service admin)
keycloak.admin.username=admin
keycloak.admin.password=admin

# Spring Security OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/scolarite
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/scolarite/protocol/openid-connect/certs

# Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.jwt=DEBUG
logging.level.org.keycloak=DEBUG


# CORS for Angular
cors.allowed-origins=http://localhost:4201
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Content-Type
cors.allow-credentials=true

